api_temakin/urls.py
from django.contrib import admin
from django.urls import path, include
from management import views
from Pedidos import views 

urlpatterns = [
    path('admin/', admin.site.urls),
    path('orders/',include('Pedidos.urls')),
    path('',include('management.urls'))
]

delivery_materiais/urls.py
from django.contrib import admin
from django.urls import path, include
from main import views

urlpatterns = [
	path('admin/', admin.site.urls),
	path('',include('main.urls'))
]

main/urls.py
from django.urls import path, include
from . import views


app_name = 'main'

gerenciador_patterns = [
    path("", views.HomeGerenciadorView.as_view(), name = "gerenciador_home"),
    path("entregas/", views.EntregaGerListView.as_view(), name = "gerenciador_entregas"),
    path("lojas/", views.LojaGerListView.as_view(), name = "gerenciador_lojas"),
    path("funcionarios/", views.FuncionarioGerListView.as_view(), name = "gerenciador_funcionarios"),
    path("veiculos/", views.VeiculoGerListView.as_view(), name = "gerenciador_veiculos"),
    path("objetos/", views.ObjetoGerListView.as_view(), name = "gerenciador_objetos"),
    path("enviar/<int:pk>", views.EnviarEntrega, name = "gerenciador_enviar_entrega"),

    path("create_funcionario/", views.CreateFuncionarioView.as_view(), name = "create_funcionario"),
    path("create_objeto/", views.CreateObjetoView.as_view(), name = "create_objeto"),
    path("create_veiculo/", views.CreateVeiculoView.as_view(), name = "create_veiculo"),
    path("create_entrega/", views.CreateEntregaView.as_view(), name = "create_entrega"),
    path("create_loja/", views.CreateLojaView.as_view(), name = "create_loja"),
]

urlpatterns  = [
	path('', views.HomeView.as_view()),
	path('home/', views.HomeView.as_view(), name = 'home'),
    path('login/',views.LoginView.as_view(),name ='login'),
    path('logout/',views.LogoutRedirectView.as_view(),name = 'logout'),
    path('list/',views.EntregaListView.as_view(),name='entregas_lista'),
    path('list/<int:pk>/detail/',views.EntregaDetailView.as_view(),name='entrega_detail'),
    path('list/<int:pk>/detail/produtos',views.EntregaDetailProdutosView.as_view(),name='entrega_detail_produtos'),
    path('list/<int:pk>/detail/funcionarios',views.EntregaDetailFuncionariosView.as_view(),name='entrega_detail_funcionarios'),
    path('gerenciador/', include(gerenciador_patterns))
]

templates/home/home.html
{% extends "index.html" %}

{% block title %} Home {% endblock %}

{% block content %}

    <div class = conteiner>
        <h3> Home de Usuario</h3>
            <p> Parabens voce foi atenticado com sucesso {% if request.user.is_authenticated %} {{ request.user.first_name  }} {% endif %}</p>
            <a class = "btn btn-primary" href="{%url 'main:logout' %}">Logout</a>
    </div>
    <br>
    <div class= conteiner>
        {%if user.is_superuser %}
            <a class = "btn btn-primary" href="{%url 'main:gerenciador_home' %}"\>Gerenciamento de Entregas</a>
        {%else%}
            <a class ="btn btn-primary" href="{%url 'main:entregas_lista' %}"\>Listagem de Endereços</a>
        {% endif %}
    </div>



{% endblock %}