api_temakin/urls.py
from django.contrib import admin
from django.urls import path, include
from management import views
from Pedidos import views 

urlpatterns = [
    path('admin/', admin.site.urls),
    path('orders/',include('Pedidos.urls')),
    path('',include('management.urls'))
]

delivery_materiais/urls.py
from django.contrib import admin
from django.urls import path, include
from main import views

urlpatterns = [
	path('admin/', admin.site.urls),
	path('',include('main.urls'))
]

main/urls.py
from django.urls import path, include
from . import views


app_name = 'main'

gerenciador_patterns = [
    path("", views.HomeGerenciadorView.as_view(), name = "gerenciador_home"),
    path("entregas/", views.EntregaGerListView.as_view(), name = "gerenciador_entregas"),
    path("lojas/", views.LojaGerListView.as_view(), name = "gerenciador_lojas"),
    path("funcionarios/", views.FuncionarioGerListView.as_view(), name = "gerenciador_funcionarios"),
    path("veiculos/", views.VeiculoGerListView.as_view(), name = "gerenciador_veiculos"),
    path("objetos/", views.ObjetoGerListView.as_view(), name = "gerenciador_objetos"),
    path("enviar/<int:pk>", views.EnviarEntrega, name = "gerenciador_enviar_entrega"),

    path("create_funcionario/", views.CreateFuncionarioView.as_view(), name = "create_funcionario"),
    path("create_objeto/", views.CreateObjetoView.as_view(), name = "create_objeto"),
    path("create_veiculo/", views.CreateVeiculoView.as_view(), name = "create_veiculo"),
    path("create_entrega/", views.CreateEntregaView.as_view(), name = "create_entrega"),
    path("create_loja/", views.CreateLojaView.as_view(), name = "create_loja"),
]

urlpatterns  = [
	path('', views.HomeView.as_view()),
	path('home/', views.HomeView.as_view(), name = 'home'),
    path('login/',views.LoginView.as_view(),name ='login'),
    path('logout/',views.LogoutRedirectView.as_view(),name = 'logout'),
    path('list/',views.EntregaListView.as_view(),name='entregas_lista'),
    path('list/<int:pk>/detail/',views.EntregaDetailView.as_view(),name='entrega_detail'),
    path('list/<int:pk>/detail/produtos',views.EntregaDetailProdutosView.as_view(),name='entrega_detail_produtos'),
    path('list/<int:pk>/detail/funcionarios',views.EntregaDetailFuncionariosView.as_view(),name='entrega_detail_funcionarios'),
    path('gerenciador/', include(gerenciador_patterns))
]

main/models.py
from django.db import models
from django.contrib.auth.models import User
import time
from datetime import timedelta
import datetime as dt
from django.utils.timezone import utc

REQUEST_TYPES = (
	('Pregos','pregos'),
	('Canos de PVC','canos de pvc'),
	('Fios de Cobre','fios de cobre'),
	('Tabuas de Madeira','tabuas de madeira'),
	('Massa de Revestimento','massa'),
	('Cimento','cimento'),
	('Tijolos','tijolos')
)

DELIVERY_TYPES = (
	('MEP','Maquinario Extremamente Pesado'),
	('MP','Maqunario Pesado'),
	('NN','Nao Necessita')
)

ROLE_TYPES = (
	('CA','Carregador'),
	('ODMD','Operador de Maquina'),
	('MC', 'Motorista de Caminhao')
)

STATES_CHOICES = (
	('AC', 'Acre'),
	('AL', 'Alagoas'),
	('AP', 'Amapá'),
	('AM', 'Amazonas'),
	('BA', 'Bahia'),
	('CE', 'Ceará'),
	('DF', 'Distrito Federal'),
	('ES', 'Espírito Santo'),
	('GO', 'Goiás'),
	('MA', 'Maranhão'),
	('MT', 'Mato Grosso'),
	('MS', 'Mato Grosso do Sul'),
	('MG', 'Minas Gerais'),
	('PA', 'Pará'),
	('PB', 'Paraíba'),
	('PR', 'Paraná'),
	('PE', 'Pernambuco'),
	('PI', 'Piauí'),
	('RJ', 'Rio de Janeiro'),
	('RN', 'Rio Grande do Norte'),
	('RS', 'Rio Grande do Sul'),
	('RO', 'Rondônia'),
	('RR', 'Roraima'),
	('SC', 'Santa Catarina'),
	('SP', 'São Paulo'),
	('SE', 'Sergipe'),
	('TO', 'Tocantins'),
)

class Funcionario(models.Model):
	nome = models.CharField(
		max_length= 30,
		default = "Arnaldao Sangue Bom"
	)

	funcao = models.CharField(
		max_length= 50,
		default = "nenhuma",
		choices = ROLE_TYPES
	)

	em_uso = models.BooleanField(
		default = False
	)

	def __str__(self):
		return "%s, %s"%(self.nome, self.funcao)

	class Meta:
		verbose_name_plural = "Funcionarios"
	
class Objeto(models.Model):
	objeto = models.CharField(
		max_length = 25,
		default= "esperando",
		choices = REQUEST_TYPES
	)

	espaco = models.IntegerField(
		null = True
	)

	quantidade = models.IntegerField(
		null = True
	)

	peso = models.IntegerField(
		default = 000
	)

	def __str__(self):
		return "%d %s"%(self.quantidade, self.objeto)

	def get_espaco_total(self):
		return (self.espaco * self.quantidade)
	
	def calcula_peso(self):
		peso_final = self.peso * self.quantidade
		return peso_final
	
	class Meta:
		verbose_name_plural = "Objetos"

class Veiculo(models.Model):
	placa = models.CharField(
		max_length = 40,
		default = ""
	)

	espaco_usado = models.IntegerField(
		default = 0
	)

	capacidade = models.IntegerField(
		default = 0000
	)

	em_uso = models.BooleanField(
		default = False
	)

	produtos = models.ManyToManyField(
		Objeto
	)

	def retorna_carga(self):
		bol = False
		cap = self.capacidade
		if cap <= 2500:
			bol = True
			return "Veiculo de baixa capacidade de carga"
		elif cap < 2500 and cap <= 5000:
			bol = True
			return "Veiculo de média capacidade de carga"
		elif cap > 5000:
			bol = True
			return "Veiculo de alta capacidade de carga"

	def peso_total(self):
		lista = []
		for produto in self.produtos.all():
			lista.append(produto.calcula_peso())
		peso = sum(lista)
		return peso
	'''
	def carga_total(self):
		comp = self.retorna_carga()
		while(comp != True):
			return "este veiculo não suporta esta quantidade de carga"
		return self.peso_total()	
	'''
	def __str__(self):
		return "placa: %s, capacidade: %s" %(self.placa, self.capacidade)

	class Meta:
		verbose_name_plural = "Veiculos"

class Entrega(models.Model):
	descarga = models.CharField(
		max_length = 40,
		default= 'esperando',
		choices = DELIVERY_TYPES
	)

	address = models.CharField(
		max_length = 200,
		default = "endereço"
	)

	address_complement = models.CharField(
		max_length = 250,
		blank = True,
		null = True
	)

	city = models.CharField(
		max_length = 200,
		default = "city"
	)

	states = models.CharField(
		max_length = 200,
		choices = STATES_CHOICES,
		default="states"
	)

	country = models.CharField(
		max_length = 200,
		default="country"
	)

	user = models.ForeignKey(
		User,
		blank = True,
		null = True,
		on_delete = models.PROTECT
	)

	veiculo = models.ForeignKey(
		Veiculo,
		on_delete = models.CASCADE,
		null = True
	)

	produtos = models.ManyToManyField(
		Objeto
	)

	funcionarios = models.ManyToManyField(
		Funcionario
	)

	time = models.DateTimeField(
		null = True,
		blank = True
	)

	def get_time_diff(self):
		if (self.time):
			t = dt.datetime.now()
			return self.time.replace(tzinfo=None) - t
		return "ainda nao enviado"

	
	class Meta:
		verbose_name_plural = "Entregas"


	def __str__(self):
		return "%s"%(self.address)

class Loja(models.Model):
	identificacao = models.CharField(
		max_length = 200,
		default = "loja"
	)

	city = models.CharField(
		max_length = 200,
		default = "city"
	)

	states = models.CharField(
		max_length = 200,
		choices = STATES_CHOICES,
		default="states"
	)

	veiculos = models.ManyToManyField(
		Veiculo
	)

	funcionarios = models.ManyToManyField(
		Funcionario
	)

	entregas = models.ManyToManyField(
		Entrega
	)

	def get_veiculo_disponivel(self, espaco):
		for veiculo in self.veiculos.all():
			print(veiculo.em_uso, veiculo.capacidade, espaco)
			if ((not veiculo.em_uso) and (veiculo.capacidade - veiculo.espaco_usado >= espaco)):
				return veiculo
		return None
	
	def get_funcionarios_disponiveis(self):
		for funcionario in self.funcionarios.all():
			print(funcionario)
			if (not funcionario.em_uso):
				return [funcionario]
		return None

	def __str__(self):
		return ("%s" % (self.identificacao))

templates/cliente/entrega_detail.html
{% extends "index.html" %}

{% block title %} Detail {% endblock %}

{% block content %}
    <div class = "conteiner">
        <h3>
            Detalhes da Entrega
        </h3>

        <table class = "table table-bordered">
            <tbody>
                <tr>
                    <th scope = "row">Previsão de chegada</th>
                    <td>{{ object.get_time_diff }}</td>
                </tr>

                <tr>
                    <th scope = "row">tipo de maquinario</th>
                    <td>{{ object.get_descarga_display }}</td>
                </tr>

                <tr>
                    <th scope = "row">endereco</th>
                    <td>{{ object.address }}</td>
                </tr>

                <tr>
                    <th scope = "row">complemento</th>
                    <td>{{ object.address_complement }}</td>
                </tr>

                <tr>
                    <th scope = "row">cidade</th>
                    <td>{{ object.city }}</td>
                </tr>

                <tr>
                    <th scope = "row">estado</th>
                    <td>{{ object.get_states_display }}</td>
                </tr>

                <tr>
                    <th scope = "row">país</th>
                    <td>{{ object.country }}</td>
                </tr>

                <tr>
                    <th scope = "row">placa do veículo de entrega</th>
                    <td>{{ object.veiculo.placa }}</td>
                </tr>
            </tbody>
        </table>
        <p>
            <a class = "btn btn-secondary" href = "{% url 'main:entrega_detail_produtos' object.pk%}">Ver produtos</a>
            <a class = "btn btn-secondary" href = "{% url 'main:entrega_detail_funcionarios' object.pk%}">Ver funcionarios</a>
        </p>
        {% if user.is_superuser %}
        <a class= "btn btn-primary" href="{%url 'main:gerenciador_entregas' %}">Voltar</a>
        {% else %}
        <a class= "btn btn-primary" href="{%url 'main:entregas_lista' %}">Voltar</a>
        {% endif %}
    </div>
{% endblock %}

templates/cliente/entrega_detail_funcionarios.html
{% extends "index.html" %}

{% block title %} Detail {% endblock %}

{% block content %}
    <div class = "conteiner">
        <h3>
            Funcionarios
        </h3>
    <table class = "table">
        <thead>
            <tr>
                <th scope="row">Nome</th>
                <th scope="row">Funcao</th>
            </tr>
        </thead>

        <tbody>
            {% for object in object_list %}
                <tr>
                    <td>{{ object.nome }}</td>
                    <td>{{ object.get_funcao_display }}</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
    {% if user.is_superuser %}
    <a class= "btn btn-primary" href="{%url 'main:gerenciador_entregas' %}">Voltar</a>
    {% else %}
    <a class= "btn btn-primary" href="{%url 'main:entregas_lista' %}">Voltar</a>
    {% endif %}
    </div>
{% endblock %}

templates/cliente/entrega_detail_produtos.html
{% extends "index.html" %}

{% block title %} Detail {% endblock %}

{% block content %}
    <div class = "conteiner">
        <h3>
            Produtos
        </h3>

            {% for object in object_list %}
                <p>{{object}}</p>
            {% endfor %}
        {% if user.is_superuser %}
        <a class= "btn btn-primary" href="{%url 'main:gerenciador_entregas' %}">Voltar</a>
        {% else %}
        <a class= "btn btn-primary" href="{%url 'main:entregas_lista' %}">Voltar</a>
        {% endif %}
    </div>
{% endblock %}

templates/cliente/entregas_list.html
{% extends "index.html" %}

{% block title %} Listagem de Endereços {% endblock %}

{% block content %}
 <div class = "conteiner">
    <h3>Listagem de endereços</h3>
    <table class = "table">
        <thead>
            <tr>
                <th>Endereço</th>
                <th>Cidade</th>
                <th>Chegada em</th>
                <th>Estado</th>
                <th>Açoes</th>
            </tr>
        </thead>

        <tbody>
            {% for object in object_list %}
                <tr>
                    <td>{{ object.address }}</td>
                    <td>{{ object.city }}</td>
                    <td>{{ object.get_time_diff }}</td>
                    <td>{{ object.get_states_display }}</td>
                    <td>
                    <a class = "btn btn-secondary" href= "{% url 'main:entrega_detail' object.pk %}">Detalhes</a>
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
    <a class = "btn btn-primary" href ="{%url 'main:home' %}">Voltar</a>
 </div>
{% endblock %}