api_temakin/urls.py
from django.contrib import admin
from django.urls import path, include
from management import views
from Pedidos import views 

urlpatterns = [
    path('admin/', admin.site.urls),
    path('orders/',include('Pedidos.urls')),
    path('',include('management.urls'))
]

delivery_materiais/urls.py
from django.contrib import admin
from django.urls import path, include
from main import views

urlpatterns = [
	path('admin/', admin.site.urls),
	path('',include('main.urls'))
]

main/urls.py
from django.urls import path, include
from . import views


app_name = 'main'

gerenciador_patterns = [
    path("", views.HomeGerenciadorView.as_view(), name = "gerenciador_home"),
    path("entregas/", views.EntregaGerListView.as_view(), name = "gerenciador_entregas"),
    path("lojas/", views.LojaGerListView.as_view(), name = "gerenciador_lojas"),
    path("funcionarios/", views.FuncionarioGerListView.as_view(), name = "gerenciador_funcionarios"),
    path("veiculos/", views.VeiculoGerListView.as_view(), name = "gerenciador_veiculos"),
    path("objetos/", views.ObjetoGerListView.as_view(), name = "gerenciador_objetos"),
    path("enviar/<int:pk>", views.EnviarEntrega, name = "gerenciador_enviar_entrega"),

    path("create_funcionario/", views.CreateFuncionarioView.as_view(), name = "create_funcionario"),
    path("create_objeto/", views.CreateObjetoView.as_view(), name = "create_objeto"),
    path("create_veiculo/", views.CreateVeiculoView.as_view(), name = "create_veiculo"),
    path("create_entrega/", views.CreateEntregaView.as_view(), name = "create_entrega"),
    path("create_loja/", views.CreateLojaView.as_view(), name = "create_loja"),
]

urlpatterns  = [
	path('', views.HomeView.as_view()),
	path('home/', views.HomeView.as_view(), name = 'home'),
    path('login/',views.LoginView.as_view(),name ='login'),
    path('logout/',views.LogoutRedirectView.as_view(),name = 'logout'),
    path('list/',views.EntregaListView.as_view(),name='entregas_lista'),
    path('list/<int:pk>/detail/',views.EntregaDetailView.as_view(),name='entrega_detail'),
    path('list/<int:pk>/detail/produtos',views.EntregaDetailProdutosView.as_view(),name='entrega_detail_produtos'),
    path('list/<int:pk>/detail/funcionarios',views.EntregaDetailFuncionariosView.as_view(),name='entrega_detail_funcionarios'),
    path('gerenciador/', include(gerenciador_patterns))
]

management/urls.py
from django.urls import path
from . import views


app_name = 'management'
urlpatterns  = [
    path('login/',views.LoginView.as_view(),name ='login'),
    path('home/',views.HomeView.as_view(),name = 'home'),
    path('logout/',views.LogoutRedirectView.as_view(),name = 'logout'),
    path('list/',views.AddressListView.as_view(),name='address_list'),
    path('list/<int:pk>/detail/',views.AddressDetailView.as_view(),name='address_detail')
]

'''
    path('create/',views.AddressCreateView.as_view(),name='address_create'),
    path('list/<int:pk>/update/',views.AddressUpdateView.as_view(),name = 'address_update'),
    path('list/<int:pk>/destroy/',views.AddressDestroyView.as_view(),name = 'address_destroy')
'''

management/models.py
from django.contrib.auth.models import User
from django.shortcuts import reverse
from django.db import models

STATES_CHOICES = (
    ('AC', 'Acre'),
    ('AL', 'Alagoas'),
    ('AP', 'Amapá'),
    ('AM', 'Amazonas'),
    ('BA', 'Bahia'),
    ('CE', 'Ceará'),
    ('DF', 'Distrito Federal'),
    ('ES', 'Espírito Santo'),
    ('GO', 'Goiás'),
    ('MA', 'Maranhão'),
    ('MT', 'Mato Grosso'),
    ('MS', 'Mato Grosso do Sul'),
    ('MG', 'Minas Gerais'),
    ('PA', 'Pará'),
    ('PB', 'Paraíba'),
    ('PR', 'Paraná'),
    ('PE', 'Pernambuco'),
    ('PI', 'Piauí'),
    ('RJ', 'Rio de Janeiro'),
    ('RN', 'Rio Grande do Norte'),
    ('RS', 'Rio Grande do Sul'),
    ('RO', 'Rondônia'),
    ('RR', 'Roraima'),
    ('SC', 'Santa Catarina'),
    ('SP', 'São Paulo'),
    ('SE', 'Sergipe'),
    ('TO', 'Tocantins'),
)

class Address(models.Model):
    address = models.CharField(
        max_length = 200,
        default = "endereço"
    )

    CEP = models.CharField(
        max_length= 10,
        default= "00.000-000"
    )
    
    address_complement = models.CharField(
        max_length = 250,
        blank = True,
        null = True
    )
    
    city = models.CharField(
        max_length = 200,
        default = "city"
    )
    
    states = models.CharField(
        max_length = 200,
        choices = STATES_CHOICES,
        default="states"
    )
    
    country = models.CharField(
        max_length = 200,
        default="country"
    )
    
    user = models.ForeignKey(
        User,
        on_delete = models.PROTECT
    )

    class Meta:
        verbose_name_plural = 'Endereços'
    
    @property
    def address_complement_normalaized(self):
        return '' if self.address_complement is None else self.address_complement

    def get_absolute_url(self):
        return reverse('management:address_detail', kwargs ={'pk':self.pk})
    
    def __str__(self):
        return "%s, %s ,%s"%(self.address,self.city,self.country)

management/forms.py
from django import forms
from .models import STATES_CHOICES, Address

class AddressForm(forms.ModelForm):
    class Meta:
        model = Address
        fields = ('address','address_complement','city','states','country')
        widgets = {
            'address':forms.TextInput(attrs={'class':'form-control'}),
            'address_complement':forms.TextInput(attrs={'class':'form-control'}),
            'city':forms.TextInput(attrs={'class':'form-control'}),
            'states':forms.Select(attrs={'class':'form-control'}),
            'country':forms.TextInput(attrs={'class':'form-control'})
        }

management/views.py
from django.shortcuts import render, redirect, reverse
from django.contrib.auth import authenticate, login as django_login, logout as django_logout
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
from .models import Address
from .forms import AddressForm
from django.views.generic import TemplateView,View,RedirectView,ListView, DetailView
from django.utils.decorators import method_decorator
from django.contrib.auth.mixins import LoginRequiredMixin 
from api_temakin.settings import LOGIN_URL
from django.urls import reverse_lazy
from Pedidos.models import Entrega
from django.contrib.auth.models import User

class FormSubmittedInContextMixin:
    def form_invalid(self,form):
        return self.render_to_reponse(self.get_contenxt_data(form= form, form_sumitted = True))

class LoginView(TemplateView):
    template_name = 'management/auth/login.html'
     
    def post(self,request,*agrs,**kwargs):
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username = username,password=password)

        if user:
            django_login(request,user)
            return render(request,'management/home.html')
        else:
            message = 'Credenciais invalidas'
            return render(request,self.template_name,{'message':message})

class HomeView(LoginRequiredMixin,TemplateView):
    template_name = 'management/home.html'


class LogoutRedirectView(LoginRequiredMixin,RedirectView):
    url = '/login/'

    def get(self, request, *args, **kwargs):
        django_logout(request)
        return super().get(request, *args, **kwargs)

class AddressDetailView(LoginRequiredMixin,DetailView):
    model = Entrega
    template_name = 'management/address/detail.html'


class AddressListView(LoginRequiredMixin,ListView):
    model = Entrega
    template_name = 'management/address/list.html'
    
    '''
    def get_queryset(self,*args,**kwargs):
        queryset = Entrega.objects.filter(user = self.request.user)
    '''

'''
class AddressCreateView(LoginRequiredMixin,FormSubmittedInContextMixin,CreateView):
    model = Address
    form_class = AddressForm 
    template_name = 'management/address/create.html'
    success_url =  reverse_lazy(('management:address_list'))

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)

class AddressUpdateView(UpdateView, LoginRequiredMixin, FormSubmittedInContextMixin):
    model = Address
    form_class = AddressForm
    template_name = 'management/address/update.html'

class AddressDestroyView(LoginRequiredMixin,DeleteView):
    model = Address
    template_name = 'management/address/destroy.html'
    success_url =  reverse_lazy(('management:address_list'))
'''

templates/management/address/create.html
{% extends "index.html" %}

{% block title %} Creation {% endblock %}

{% block content %}
    <div class = "conteiner">
        <h3> Novo Endereço</h3>
        <form action = "{% url 'management:address_create' %}"  method ="post" {% if form_submitted %} class="was-validated" {% endif %}>
            {% csrf_token %}
            {% include "management/form/padron.html" %}
            <button type = "submit" class = "btn btn-primary">Criar</button>
            <button type = "menu" class="btn btn-primary" href="{%url 'management:address_list' %}">Voltar</button>
        </form>
    </div>
{% endblock %}

templates/management/address/destroy.html
{% extends "index.html" %}

{% block title %} Deletion - {% endblock %}

{% block content %}
    <div class = "conteiner">
        <h3> Excluir Endereço</h3>
        <form action = "{% url 'management:address_destroy' object.pk%}" method ="post"}>
            {% csrf_token %}
            <fieldset disabled>
                {% include "management/form/padron.html" %}
            </fieldset>
            <button type = "submit" class = "btn btn-primary">Excluir</button>
        </form>
    </div>
{% endblock %}

templates/management/address/detail.html
{% extends "index.html" %}

{% block title %} Detail {% endblock %}

{% block content %}
    <div class = "conteiner">
        <h3>
            Detalhes dos Funcionarios
        </h3>

        <table class = "talbe table-bordered">
            <tbody>
                <tr>
                    <th scope = "row">Matricula</th>
                    <td>{{ object.matricula }}</td>
                </tr>

                <tr>
                    <th scope = "row">nome</th>
                    <td>{{ object.nome }}</td>
                </tr>

                <tr>
                    <th scope = "row">Funçao</th>
                    <td>{{ object.Funçao }}</td>
                </tr>
            </tbody>
        </table>
        <a href="{%url 'management:address_list' %}">Voltar</a>
    </div>
{% endblock %}

templates/management/address/list.html
{% extends "index.html" %}

{% block title %} Listagem de Endereços {% endblock %}

{% block content %}
 <div class = "conteiner">
    <h3>Listagem de endereços</h3>
    <table class = "table">
        <thead>
            <tr>
                <th>Endereço</th>
                <th>Status</th>
                <th>Cidade</th>
                <th>Estado</th>
                <th>Açoes</th>
            </tr>
        </thead>

        <tbody>
            {% for address in object_list %}
                <tr>
                    <td>
                        <a>{{ address.address }}</a>
                    </td>
                    <td>{{ address.status }}</td>
                    <td>{{ address.city }}</td>
                    <td>{{ address.states }}</td>
                    <td>
                    <a href= "{% url 'management:address_detail' address.pk %}">Detalhes</a>
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
    <a class = "btn btn-primary" href ="{%url 'management:home' %}">Voltar</a>
 </div>
{% endblock %}

templates/management/address/update.html
{% extends "index.html" %}

{% block title %} Update {% endblock %}

{% block content %}
    <div class = "conteiner">
        <h3> Editar Endereço</h3>
        <form action = "{% url 'management:address_update' address.id %}" method ="post" {% if form_submitted %} class="was-validated" {% endif %}>
            {% csrf_token %}
            {% include "management/form/padron.html" %}
            <button type = "submit" class = "btn btn-primary">Atualizar</button>
        </form>
    </div>
{% endblock %}